// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MonitoringWebService.Models
{
    public partial class tblServerGroups
    {
        [Key]
        public int Id { get; set; }
        public int GroupId { get; set; }
        
        public string Servers { get; set; }
        public int? CpuWarning { get; set; }
        public int? CpuCritical { get; set; }
        public int? MemoryWarning { get; set; }
        public int? MemoryCritical { get; set; }
        public int? NetworkWarning { get; set; }
        public int? NetworkCritical { get; set; }
        public int? DiskWarning { get; set; }
        public int? DiskCritical { get; set; }
        public bool IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Createdon { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
    }
}