// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace MonitoringWebService.Models
{
    public partial class tblTimerIntervals
    {
        [Key]
        public int Id { get; set; }
        public int? MonitoringTimerInterval { get; set; }

        public int? MonitoringJsonUploadTimerInterval { get; set; }
        public int? HeartBeatInterval { get; set; }
        public int? NotificationTimerInterval { get; set; }
        public int? PurgeTimerInterval { get; set; }
        public int? ReportingTimerInterval { get; set; }
        public int? DeviceMonitoringInterval { get; set; }
        public bool IsActive { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
    }
}